### ISSUE TITLE
OGC API Links reference - consistency of specfication text and schemas

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/ogc-feat-geo-json#117] opened 2024-01-09 01:59 UTC
Section D mentions by name, but not by a reference "OGC API Link object"

a link schema is present at https://beta.schemas.opengis.net/json-fg/link.json

Section **7.8.2. Description** references the links object inherited from API Features, but the schema as referenced in the document references https://beta.schemas.opengis.net/json-fg/featurecollection.json which in turn references this local copy.

Both the text and machine readable schemas should explicity reference the authoritative API Features definitions where interoperability is intended.  

There is a complication that OAS 3.0 does not support relative paths in schemas included by reference - it may be necessary to use absolute URIs - or to generate an OAS 3.0 compliant version from more elegant and modern schemas - e.g. https://opengeospatial.github.io/bblocks/annotated-schemas/geo/json-fg/feature/schema-oas3.0.json

**Comment by cportele** [comment] 2024-02-19 14:57
Referencing the [link schema from OGC API Features](https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml) is not possible, because it is an OpenAPI 3.0 schema, while the JSON-FG schema is JSON Schema.

Common has specified [a JSON Schema for links](https://schemas.opengis.net/ogcapi/common/part1/1.0/openapi/schemas/link.json), but that uses the old draft 07 and that might also be an error since the schema is in a folder "openapi".

**Comment by cportele** [comment] 2024-02-19 15:30
Actually, the issue has been overcome by events. In version 0.2, links are no longer used: https://github.com/opengeospatial/ogc-feat-geo-json/tree/main/core/schemas.

Once v0.2.2 has been published (this week), we will request an update of https://beta.schemas.opengis.net/json-fg/ and the `link.json` schema will be removed.

**Comment by cportele** [comment] 2024-02-19 16:11
Meeting 2024-02-19: Close the issue, the link.json schema is no longer part of JSON-FG, so the issue is no longer relevant.

**Closed by cportele** 2024-02-19 16:11 UTC
